version: 2
project_name: helm-schema-gen

builds:
  - id: helm-schema-gen
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildDate={{.Date}} -X main.CommitHash={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
