name: GoReleaser

on:
  repository_dispatch:
    types: [goreleaser]


permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'repository_dispatch' && format('v{0}', github.event.client_payload.version) || '' }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}